### PR TITLE
Removed scrollbar, improved responsiveness

### PR DESCRIPTION
**Pull request by JaKrau**
Added new package / plugin to remove scrollbar from Live Chat page, and improved responsiveness.

### CODE REVIEW

**Review by Torvec — CHANGES_REQUESTED** [review]
On line 182, there is class called `overflow-y-scroll `that should be changed to `overflow-y-hidden` and also the `no-scrollbar` class can be removed. You don't need that package. Everything else you did looks good though.

**Comment by JaKrau** [comment]
Looking into that, thanks!

**Comment by JaKrau** [comment]
Reopening, scroll functionality intact with "scrollbar-none".

**Comment by JaKrau** [comment]
Closing, for non-packaged solution was found by Ed!

**Pull request closed without merging**
